@isTest
private class esbFrontierComSharedtypeTest {
    private static testmethod void unit(){
    	esbFrontierComSharedtype.ExecutionStatusMessage esm = new esbFrontierComSharedtype.ExecutionStatusMessage();
    	esbFrontierComSharedtype.ResponseHeader resh = new esbFrontierComSharedtype.ResponseHeader();
    	esbFrontierComSharedtype.RequestHeader reqh = new esbFrontierComSharedtype.RequestHeader();
    	esbFrontierComSharedtype.ForEsbUseOnly esb = new esbFrontierComSharedtype.ForEsbUseOnly();
    	esbFrontierComSharedtype.SecurityInfo si = new esbFrontierComSharedtype.SecurityInfo();
    	/*
    	esbFrontierComSharedtype.Address = new esbFrontierComSharedtype.Address();
    	esbFrontierComSharedtype.esbFrontierComSharedtype.TimePeriod = new esbFrontierComSharedtype.TimePeriod();
    	esbFrontierComSharedtype.GlobalPosition = new esbFrontierComSharedtype.GlobalPosition();
    	esbFrontierComSharedtype.EnvelopeAddress = new esbFrontierComSharedtype.EnvelopeAddress();
    	esbFrontierComSharedtype.AccountIdRequest = new esbFrontierComSharedtype.AccountIdRequest();
    	esbFrontierComSharedtype.TelephoneNumberAsId = new esbFrontierComSharedtype.TelephoneNumberAsId();
    	esbFrontierComSharedtype.EmailAccountId = new esbFrontierComSharedtype.EmailAccountId();
    	esbFrontierComSharedtype.GivenAndFamilyName = new esbFrontierComSharedtype.GivenAndFamilyName();
    	esbFrontierComSharedtype.QuantityDecimal = new esbFrontierComSharedtype.QuantityDecimal();
    	esbFrontierComSharedtype.AddressChoice = new esbFrontierComSharedtype.AddressChoice();
    	esbFrontierComSharedtype.ServiceAddressMasterId = new esbFrontierComSharedtype.ServiceAddressMasterId();
    	*/
    }
}