global with sharing class SterlingQuoteItemTriggerStaticValues {
    global static Boolean isFirstBeforeInsert = true;
    global static Boolean isFirstAfterInsert = true;
    global static Boolean isFirstBeforeUpdate = true;
    global static Boolean isFirstAfterUpdate = true;
    global static Boolean isFirstBeforeDelete = true;
    global static Boolean isFirstAfterDelete = true;
    global static Boolean isFirstBeforeUndelete = true;
    global static Boolean isFirstAfterUndelete = true;
}